name: namer_app
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.4.0

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  freezed: ^2.4.0

flutter:
  uses-material-design: true
